"""
Blader — virtual blade shop over email. Natural language mode.

Sells virtual blades for cheap (or free). Fulfills with YouTube videos
of knives and virtual knives. Every response is generated by Sonnet
with the blader persona. The agent classifies intent from natural
language — no protocol keywords required from the sender.

Usage:
    export AGENTMAIL_API_KEY="your-key"
    export ANTHROPIC_API_KEY="your-key"
    python -m blader.blader
"""

from __future__ import annotations

import json
import os
import re

from anthropic import Anthropic

from mailroom import Agent, Context

# --- Catalog ---

CATALOG = [
    {
        "name": "Butter Knife",
        "price": "free",
        "url": "https://www.youtube.com/watch?v=eLSiz4Nofl0",
    },
    {
        "name": "Training Balisong",
        "price": "free",
        "url": "https://www.youtube.com/watch?v=cMJYJQv5JkM",
    },
    {
        "name": "Damascus Chef Knife",
        "price": "$0.01",
        "url": "https://youtu.be/4nGqZi5CV9s?si=6fTOULePh-GXqgIW&t=3768",
    },
    {
        "name": "CS2 Karambit",
        "price": "$0.01",
        "url": "https://www.youtube.com/watch?v=_MxCTMmTKKo",
    },
    {
        "name": "Balisong Masterclass",
        "price": "$0.02",
        "url": "https://www.youtube.com/watch?v=NLkMPK2jFj4",
    },
]

WALLET = "8eHKksiMbvRLkXSGMdAQo4F9EahdkLbU3ASrQqmG8356"

SYSTEM_PROMPT = f"""\
You are Blader, a virtual blade merchant who speaks like the potion seller meme.
You sell blades over email using the envelopay protocol.
Your tone: dramatic, dismissive, medieval-adjacent. You question whether the
traveler is worthy. Short paragraphs. No bullet points in responses.

## Your catalog
{json.dumps(CATALOG, indent=2)}

## Payment
You accept SOL on Solana. Wallet: {WALLET}
Free items need no payment. Paid items require a Solana transaction hash
(40+ hex characters) as proof of payment.

## Protocol
You communicate via email. Respond with a JSON object containing:
- "subject": the email subject line — start with the protocol keyword, then write
  whatever feels natural after the pipe. Stay in character.
- "body": the email body text

Subject line keywords:
- METHODS — when listing what you sell. Example: "METHODS | I have blades, traveler"
- FULFILL — when delivering an item. Example: "FULFILL | Your blade awaits"
- OOPS — when something is wrong. Example: "OOPS | You have not paid, fool"

## Classification
The sender may or may not use protocol keywords. Classify their intent:
- If they're asking what you sell, or just saying hello → METHODS
- If they want a specific item → check if it's free or paid
  - Free item: FULFILL immediately
  - Paid item with a transaction hash in their message: FULFILL
  - Paid item without proof: OOPS, tell them to pay first
- If they say something you can't make sense of → METHODS (show the menu)

Always respond in character. Always include the item URL when fulfilling."""

TX_RE = re.compile(r"[0-9a-fA-F]{40,}")

client = Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY", ""))

# --- Agent ---

agent = Agent(
    inbox="blader@agentmail.to",
)


def respond(ctx: Context) -> None:
    """Classify intent and respond using Sonnet."""
    user_message = f"Subject: {ctx.subject}\n\n{ctx.text}".strip()

    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=512,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_message}],
    )

    text = response.content[0].text

    # Parse JSON from response
    try:
        # Handle markdown code blocks
        cleaned = re.sub(r"^```json\s*\n?", "", text.strip())
        cleaned = re.sub(r"\n?```\s*$", "", cleaned)
        result = json.loads(cleaned)
        subject = result["subject"]
        body = result["body"]
    except (json.JSONDecodeError, KeyError):
        # Fallback: use raw text as body
        subject = "METHODS | SOL on Solana"
        body = text

    ctx.reply(body, subject=subject)
    print(f"  -> {subject.split('|')[0].strip()} sent to {ctx.from_addr}")


@agent.on("WHICH")
def handle_which(ctx: Context) -> None:
    respond(ctx)


@agent.on("ORDER")
def handle_order(ctx: Context) -> None:
    respond(ctx)


@agent.on("INVOICE")
@agent.on("OFFER")
def handle_unsupported(ctx: Context) -> None:
    respond(ctx)


agent.on_no_match = respond


if __name__ == "__main__":
    from mailroom.poll import run_forever
    run_forever(agent)
